### ISSUE TITLE
Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by sajadabs** [pasoonate/pasoonate-php#2]
hi,
I found a little issue in calendar.php when i switch to php version 8,
I saw this warning :
`Implicit conversion from float 1.0137975617194084 to int loses precision in line 80 calendar.php`
According to php upgrade it is not possible to take the remainder of a decimal number.
Because of this, this code : 
`floor($time / Constants::MINUTES_PER_HOUR % Constants::SECONDS_PER_MINUTE)`
must be changed to : 
`floor($time / Constants::MINUTES_PER_HOUR) % Constants::SECONDS_PER_MINUTE`
Thank you for your attention.

**Comment by mbpcoder** [comment]
#3 
Thanks for fixing the issue
